name: build-sphinx-to-gh-pages

env:
  GITHUB_ACTOR: broderickpt
  GITHUB_REPOSITORY: broderickpt/broderickpt.github.io
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [master]

jobs:
  build_sphinx_job:
    runs-on: ubuntu-latest
    ##  container: debian:buster-slim

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          set -x
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get -qqq update
          sudo apt-get install -y build-essential ca-certificates cmake pkg-config wget
          sudo apt-get install -y python3.8
          sudo apt-get install -y python3-pip
          pip install -U Sphinx 
          echo $PATH
          PATH=$PATH:/home/runner/.local/bin
          echo $PATH
          pip install sphinx_rtd_theme 
          pip install breathe
          which sphinx-build
          sudo apt-get install -y doxygen
          sudo curl -L -o /usr/local/bin/cmake-easyinstall https://git.io/JvLxY
          sudo chmod a+x /usr/local/bin/cmake-easyinstall
          export CEI_SUDO="sudo"

      - name: Clone repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/checkout@v2
        with:
          path: doc-build

      - name: build the docs
        run: |
          set -x
          echo $PATH
          PATH=$PATH:/home/runner/.local/bin
          echo $PATH
          which sphinx-build
          cd doc-build
          mkdir build && cd build
          cmake ..
          make Sphinx
        shell: bash

      - name: Run build script for Sphinx pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          cd "../docs/buildsite.sh"
        shell: bash
