name: build-sphinx-to-gh-pages

env:
  GITHUB_ACTOR: broderickpt
  GITHUB_REPOSITORY: broderickpt/broderickpt.github.io
  GITHUB_TOKEN: ${{ secrets.CREATE_DEMO_SECRET }}

on: 
  push:
    branches: [ main ]


jobs:

  build_sphinx_job:
    runs-on: ubuntu-latest
    ##  container: debian:buster-slim

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: |
        set -x
	export DEBIAN_FRONTEND=noninteractive
        sudo apt-get -qqq update
        sudo apt-get install -y build-essential ca-certificates cmake pkg-config wget
	sudo apt-get install -y git
        sudo apt-get install python3.8
        export CEI_SUDO="sudo"

    - name: Clone repository
      env:
        GITHUB_TOKEN: ${{ secrets.CREATE_DEMO_SECRET }}
      run: |
        set -x
        git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
      shell: bash

    - name: Run build script for Sphinx pages
      env:
        GITHUB_TOKEN: ${{ secrets.CREATE_DEMO_SECRET }}
        run: "docs/buildsite.sh"
        shell: bash
